trigger:
- docker

variables:
  location: 'eastus'
  rgName: 'DefaultResourceGroup-EUS'
  imageName: 'chadmcrowell/javascript-docker'
  webAppName: 'acgwebapp'

stages:

- stage: Build
  jobs:
  - job: Build
    pool:
      name: 'default'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: build
        Dockerfile: app/Dockerfile
      
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: '$(imageName)'
        command: 'push'

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      name: 'default'
    steps:
    - checkout: none

    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Azure App Service'
      inputs:
        azureSubscription: 'AzureSC'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(rgName)'
        location: 'East US'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/linuxacademy/content-az400-lab-resources/docker/ArmTemplates/container-webapp-template.json'
        overrideParameters: '-registryName $(imageName) -webAppName $(webAppName)'
        
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'AzureSC'
        appName: '$(webAppName)'
        containers: '$(imageName):$(Build.BuildId)'
